#exclude:      [
#  "README.md",
#  "*.map",
#  "*.scss"
#]
url: //petrosh.github.io/primer
baseurl: ""

permalink:    pretty

highlighter:  rouge

markdown: kramdown

kramdown:
  auto_ids: true

github:
  repo: https://github.com/petrosh/primer
