#exclude:      [
#  "README.md",
#  "*.map",
#  "*.scss"
#]
url: //petrosh.github.io/primer
baseurl: /primer
permalink: pretty
# or permalink: /:categories/:title/
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
github:
  repo: https://github.com/petrosh/primer
