<<<<<<< HEAD
exclude:      [
  "README.md",
  "*.map",
  "*.scss"
]

permalink:    pretty

highlighter:  rouge

markdown: kramdown

kramdown:
  auto_ids: true

=======
#exclude:      [
#  "README.md",
#  "*.map",
#  "*.scss"
#]
url: //petrosh.github.io/primer
baseurl: /primer
permalink: pretty
# or permalink: /:categories/:title/
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
>>>>>>> origin/master
github:
  repo: https://github.com/petrosh/primer
